version: "3.8"

volumes:
  postgres:

services:
  stripe-cli:
    image: stripe/stripe-cli:latest
    container_name: stripe-cli
    restart: unless-stopped
    command: "listen --forward-to http://api:5000/stripe/webhook/"
    env_file:
      - dev.env

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - 8080:8080

  db:
    container_name: db
    image: postgres:latest
    restart: unless-stopped
    env_file:
      - dev.env
    volumes:
      - postgres:/var/lib/postgresql/data

  api:
    container_name: api
    build: ./api
    volumes:
      - ./api:/code
    stop_signal: SIGKILL
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - dev.env
    
  browser-client:
    container_name: browser-client
    build: 
      context: ./browser-client
      target: install-requirements
    command: "npm run start"
    ports:
      - 3000:3000
    volumes: 
      - ./browser-client:/code
    restart: unless-stopped
