version: "3.8"

services:
  nginx-proxy:
    container_name: nginx-proxy
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./default.conf.template:/etc/nginx/templates/default.conf.template:ro

  stripe-cli:
    image: stripe/stripe-cli:latest
    container_name: stripe-cli
    restart: unless-stopped
    command: "listen --forward-to api:5000/stripe/webhook/"
    env_file:
      - stripe_cli.env

  api:
    container_name: api
    build: ./api
    volumes:
      - ./api:/code
    stop_signal: SIGKILL
    restart: unless-stopped
    
  browser-client:
    container_name: browser-client
    build: 
      context: ./browser-client
      target: install-requirements
    command: "npm run start"
    volumes: 
      - ./browser-client:/code
    restart: unless-stopped
